import { ArrowRight, BookOpen, CalendarDays, ClipboardList, Coins, LayoutGrid, Star, UsersRound } from "lucide-react";
import "../styles/admin-summary.css";
type Metric = {label:string;value:number;detail:string};
type Props = {kpis:Metric[];revenue:number;loading:boolean;openModule:(module:string)=>void;enrollmentDates:string[];revenueRecords:{date:string;amount:number}[]};
export function AdminSummary({kpis,revenue,loading,openModule,enrollmentDates,revenueRecords}:Props){
 const now=new Date();const start=new Date(now.getFullYear(),now.getMonth(),1);const dayCount=now.getDate();
 const find=(label:string)=>kpis.find(item=>item.label===label);
 const cards=[{label:"Students",icon:UsersRound,tone:"violet",module:"Students",metric:find("Students")},{label:"Programs",icon:BookOpen,tone:"blue",module:"Programs",metric:find("Programs")},{label:"Enrollments",icon:ClipboardList,tone:"green",module:"Enrollments",metric:find("Enrollments"),records:enrollmentDates.map(date=>({date,amount:1}))},{label:"Revenue",icon:Coins,tone:"gold",module:"Payments",metric:{value:revenue,detail:"Verified payments"},records:revenueRecords},{label:"Reviews",icon:Star,tone:"pink",module:"Projects",metric:find("Reviews")},{label:"Categories",icon:LayoutGrid,tone:"violet",module:"Categories",metric:find("Categories")}];
 return <section className="admin-summary" aria-label="Academy summary" aria-busy={loading}>
 <header className="admin-summary-welcome"><div className="admin-summary-copy"><span>ADMIN DASHBOARD</span><h1>Welcome back, Admin <span className="admin-summary-wave">&#128075;</span></h1><p>Here's an overview of your academy at a glance.</p></div><div className="admin-summary-date"><span><CalendarDays size={26}/></span><p>{now.toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"short",year:"numeric"})}<br/>Have a productive day!</p></div><div className="admin-summary-art" aria-hidden="true"><span>Education<br/>creates<br/>opportunities<i/></span><img src="/assets/admin-books-plant.png" alt="" width="1536" height="1024"/></div></header>
 <div className="admin-summary-grid">{cards.map(card=>{const Icon=card.icon;const records=card.records;const values=records?Array.from({length:Math.max(2,dayCount)},(_,index)=>records.filter(item=>new Date(item.date)>=start&&new Date(item.date)<new Date(now.getFullYear(),now.getMonth(),Math.min(index+2,dayCount+1))).reduce((sum,item)=>sum+item.amount,0)):null;const max=values?Math.max(1,...values):1;const points=values?.map((value,index)=>`${2+index*160/(values.length-1)},${43-value/max*36}`).join(" ");return <button key={card.label} className={`admin-summary-card admin-summary-card--${card.tone}`} onClick={()=>openModule(card.module)}><span className="admin-summary-icon"><Icon size={30}/></span><span className="admin-summary-label">{card.label}</span><strong>{loading?"—":card.label==="Revenue"?new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number.isFinite(revenue)?revenue:0):(card.metric?.value??0).toLocaleString("en-IN")}</strong><small>{card.metric?.detail??"Current total"}</small><div className="admin-summary-card-bottom">{values?<svg viewBox="0 0 164 48" role="img" aria-label={`${card.label}: cumulative recorded activity this month`}><defs><linearGradient id={`summary-${card.label}`} x1="0" y1="0" x2="0" y2="1"><stop stopColor="currentColor" stopOpacity=".2"/><stop offset="1" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><polygon points={`2,48 ${points} 162,48`} fill={`url(#summary-${card.label})`}/><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2"/></svg>:<span className="admin-summary-snapshot">{card.label==="Reviews"?"Pending project reviews":"Current snapshot"}</span>}<span className="admin-summary-arrow"><ArrowRight size={24}/></span></div>{values&&<span className="admin-summary-chart-caption">This month</span>}</button>;})}</div>
 </section>;
}
